// ISO 3166-1 alpha-2 code for each flag name in the ILO data, which is how
// flag-icons names its SVGs (gb-eng is England). The ILO uses UN names
// ("Türkiye", "Viet Nam") and has renamed some flags over time; the older names
// stay so history rows still match. test/flags.test.js fails when the committed
// database has a flag name missing here.
export const FLAG_CODES = {
  'Algeria': 'dz',
  'Angola': 'ao',
  'Antigua and Barbuda': 'ag',
  'Australia': 'au',
  'Bahamas': 'bs',
  'Bahrain': 'bh',
  'Bangladesh': 'bd',
  'Barbados': 'bb',
  'Belize': 'bz',
  'Bolivia': 'bo',
  'Bolivia (Plurinational State of)': 'bo',
  'Brazil': 'br',
  'Bulgaria': 'bg',
  'Cabo Verde': 'cv',
  'Cambodia': 'kh',
  'Cameroon': 'cm',
  'Cayman Islands': 'ky',
  'China': 'cn',
  'Colombia': 'co',
  'Comoros': 'km',
  'Cook Islands': 'ck',
  'Croatia': 'hr',
  'Curaçao': 'cw',
  'Cyprus': 'cy',
  "Democratic People's Republic of Korea": 'kp',
  'Democratic Republic of the Congo': 'cd',
  'Denmark': 'dk',
  'Djibouti': 'dj',
  'Dominica': 'dm',
  'Ecuador': 'ec',
  'Egypt': 'eg',
  'England': 'gb-eng',
  'Equatorial Guinea': 'gq',
  'Estonia': 'ee',
  'Eswatini': 'sz',
  'Finland': 'fi',
  'France': 'fr',
  'Gabon': 'ga',
  'Gambia': 'gm',
  'Georgia': 'ge',
  'Germany': 'de',
  'Gibraltar': 'gi',
  'Greece': 'gr',
  'Guinea': 'gn',
  'Guinea-Bissau': 'gw',
  'Guyana': 'gy',
  'Haiti': 'ht',
  'Honduras': 'hn',
  'Hong Kong': 'hk',
  'Hong Kong Special Administrative Region': 'hk',
  'India': 'in',
  'Indonesia': 'id',
  'Iran': 'ir',
  'Iran (Islamic Republic of)': 'ir',
  'Isle of Man': 'im',
  'Italy': 'it',
  'Jamaica': 'jm',
  'Kenya': 'ke',
  'Kiribati': 'ki',
  'Kuwait': 'kw',
  'Latvia': 'lv',
  'Lebanon': 'lb',
  'Liberia': 'lr',
  'Libya': 'ly',
  'Malaysia': 'my',
  'Malta': 'mt',
  'Marshall Islands': 'mh',
  'Mauritania': 'mr',
  'Mauritius': 'mu',
  'Mexico': 'mx',
  'Mongolia': 'mn',
  'Montenegro': 'me',
  'Morocco': 'ma',
  'Namibia': 'na',
  'Netherlands': 'nl',
  'Netherlands (Kingdom of the)': 'nl',
  'Nicaragua': 'ni',
  'Nigeria': 'ng',
  'Niue': 'nu',
  'Oman': 'om',
  'Palau': 'pw',
  'Panama': 'pa',
  'Philippines': 'ph',
  'Portugal': 'pt',
  'Qatar': 'qa',
  'Republic of Korea': 'kr',
  'Republic of Moldova': 'md',
  'Russian Federation': 'ru',
  'Saint Kitts and Nevis': 'kn',
  'Saint Vincent and the Grenadines': 'vc',
  'Samoa': 'ws',
  'San Marino': 'sm',
  'Sao Tome and Principe': 'st',
  'Saudi Arabia': 'sa',
  'Senegal': 'sn',
  'Sierra Leone': 'sl',
  'Singapore': 'sg',
  'Slovakia': 'sk',
  'Somalia': 'so',
  'Spain': 'es',
  'Sri Lanka': 'lk',
  'Syrian Arab Republic': 'sy',
  'Togo': 'tg',
  'Tuvalu': 'tv',
  'Türkiye': 'tr',
  'Ukraine': 'ua',
  'United Arab Emirates': 'ae',
  'United Kingdom of Great Britain and Northern Ireland': 'gb',
  'United Republic of Tanzania': 'tz',
  'United States of America': 'us',
  'Uruguay': 'uy',
  'Vanuatu': 'vu',
  'Viet Nam': 'vn',
  'Zambia': 'zm',
};

export function flagCode(name) {
  const key = name?.trim();
  return key && Object.hasOwn(FLAG_CODES, key) ? FLAG_CODES[key] : null;
}
