// ISO 3166-1 alpha-2 code for each country name in the ILO data, as a ship's
// flag or a crew's nationality, which is how flag-icons names its SVGs (gb-eng
// is England). The ILO uses UN names ("Türkiye", "Viet Nam") and has renamed
// some flags over time; the older names stay so history rows still match.
// test/flags.test.js fails when the committed database has a flag or a
// nationality missing here. Yugoslavia, a nationality on older cases, is left
// out: flag-icons has no flag for it.
export const FLAG_CODES = {
  'Albania': 'al',
  'Algeria': 'dz',
  'Angola': 'ao',
  'Antigua and Barbuda': 'ag',
  'Argentina': 'ar',
  'Armenia': 'am',
  'Australia': 'au',
  'Azerbaijan': 'az',
  'Bahamas': 'bs',
  'Bahrain': 'bh',
  'Bangladesh': 'bd',
  'Barbados': 'bb',
  'Belarus': 'by',
  'Belgium': 'be',
  'Belize': 'bz',
  'Benin': 'bj',
  'Bhutan': 'bt',
  'Bolivia': 'bo',
  'Bolivia (Plurinational State of)': 'bo',
  'Bosnia and Herzegovina': 'ba',
  'Brazil': 'br',
  'Bulgaria': 'bg',
  'Burkina Faso': 'bf',
  'Cabo Verde': 'cv',
  'Cambodia': 'kh',
  'Cameroon': 'cm',
  'Canada': 'ca',
  'Cayman Islands': 'ky',
  'Chile': 'cl',
  'China': 'cn',
  'Colombia': 'co',
  'Comoros': 'km',
  'Congo': 'cg',
  'Cook Islands': 'ck',
  'Costa Rica': 'cr',
  "Côte d'Ivoire": 'ci',
  'Croatia': 'hr',
  'Cuba': 'cu',
  'Curaçao': 'cw',
  'Cyprus': 'cy',
  "Democratic People's Republic of Korea": 'kp',
  'Democratic Republic of the Congo': 'cd',
  'Denmark': 'dk',
  'Djibouti': 'dj',
  'Dominica': 'dm',
  'Dominican Republic': 'do',
  'Ecuador': 'ec',
  'Egypt': 'eg',
  'El Salvador': 'sv',
  'England': 'gb-eng',
  'Equatorial Guinea': 'gq',
  'Eritrea': 'er',
  'Estonia': 'ee',
  'Eswatini': 'sz',
  'Ethiopia': 'et',
  'Finland': 'fi',
  'France': 'fr',
  'Gabon': 'ga',
  'Gambia': 'gm',
  'Georgia': 'ge',
  'Germany': 'de',
  'Ghana': 'gh',
  'Gibraltar': 'gi',
  'Greece': 'gr',
  'Guatemala': 'gt',
  'Guinea': 'gn',
  'Guinea-Bissau': 'gw',
  'Guyana': 'gy',
  'Haiti': 'ht',
  'Honduras': 'hn',
  'Hong Kong': 'hk',
  'Hong Kong Special Administrative Region': 'hk',
  'India': 'in',
  'Indonesia': 'id',
  'Iran': 'ir',
  'Iran (Islamic Republic of)': 'ir',
  'Iraq': 'iq',
  'Ireland': 'ie',
  'Isle of Man': 'im',
  'Italy': 'it',
  'Jamaica': 'jm',
  'Jordan': 'jo',
  'Kazakhstan': 'kz',
  'Kenya': 'ke',
  'Kiribati': 'ki',
  'Kuwait': 'kw',
  'Kyrgyzstan': 'kg',
  'Latvia': 'lv',
  'Lebanon': 'lb',
  'Liberia': 'lr',
  'Libya': 'ly',
  'Liechtenstein': 'li',
  'Lithuania': 'lt',
  'Malaysia': 'my',
  'Maldives': 'mv',
  'Malta': 'mt',
  'Marshall Islands': 'mh',
  'Mauritania': 'mr',
  'Mauritius': 'mu',
  'Mexico': 'mx',
  'Mongolia': 'mn',
  'Montenegro': 'me',
  'Morocco': 'ma',
  'Myanmar': 'mm',
  'Namibia': 'na',
  'Nepal': 'np',
  'Netherlands': 'nl',
  'Netherlands (Kingdom of the)': 'nl',
  'Nicaragua': 'ni',
  'Nigeria': 'ng',
  'Niue': 'nu',
  'Oman': 'om',
  'Pakistan': 'pk',
  'Palau': 'pw',
  'Panama': 'pa',
  'Papua New Guinea': 'pg',
  'Peru': 'pe',
  'Philippines': 'ph',
  'Poland': 'pl',
  'Portugal': 'pt',
  'Qatar': 'qa',
  'Republic of Korea': 'kr',
  'Republic of Moldova': 'md',
  'Romania': 'ro',
  'Russian Federation': 'ru',
  'Saint Kitts and Nevis': 'kn',
  'Saint Lucia': 'lc',
  'Saint Vincent and the Grenadines': 'vc',
  'Samoa': 'ws',
  'San Marino': 'sm',
  'Sao Tome and Principe': 'st',
  'Saudi Arabia': 'sa',
  'Senegal': 'sn',
  'Serbia': 'rs',
  'Sierra Leone': 'sl',
  'Singapore': 'sg',
  'Slovakia': 'sk',
  'Slovenia': 'si',
  'Somalia': 'so',
  'South Africa': 'za',
  'Spain': 'es',
  'Sri Lanka': 'lk',
  'Sudan': 'sd',
  'Sweden': 'se',
  'Syrian Arab Republic': 'sy',
  'Taiwan': 'tw',
  'Tajikistan': 'tj',
  'Thailand': 'th',
  'Togo': 'tg',
  'Tunisia': 'tn',
  'Tuvalu': 'tv',
  'Türkiye': 'tr',
  'Uganda': 'ug',
  'Ukraine': 'ua',
  'United Arab Emirates': 'ae',
  'United Kingdom of Great Britain and Northern Ireland': 'gb',
  'United Republic of Tanzania': 'tz',
  'United States of America': 'us',
  'Uruguay': 'uy',
  'Uzbekistan': 'uz',
  'Vanuatu': 'vu',
  'Venezuela (Bolivarian Republic of)': 've',
  'Viet Nam': 'vn',
  'Yemen': 'ye',
  'Zambia': 'zm',
};

export function flagCode(name) {
  const key = name?.trim();
  return key && Object.hasOwn(FLAG_CODES, key) ? FLAG_CODES[key] : null;
}
